### PR TITLE
chore: implement healthchecks in containers

### PR DESCRIPTION
**Pull request by obdulia-losantos**
~Pending on:~
~https://github.com/eHealthAfrica/aether/pull/326~
~then create the new aether release `0.9.0` and~
~https://github.com/eHealthAfrica/aether-bootstrap/pull/14~
~continue with~
~https://github.com/eHealthAfrica/gather/pull/24~
~and last create the new gather release `3.0.0-rc`~

@adamvert ready! :crossed_fingers:

### CODE REVIEW

**Comment by admbtlr** [comment]
Just realised this PR is coming from a fork - any particular reason?

**Comment by obdulia-losantos** [comment]
Check the repo settings :wink: 

I'm not allowed to do anything here, either merge my PRs :scream:

**Comment by admbtlr** [comment]
Ooops, sorry about that! Fixed. 
Can you clone your your fork to a branch so that I can test it?

**Comment by obdulia-losantos** [comment]
Moved to #5

**Pull request closed without merging**
